// main/pokedex_static.c —— 离线静态图鉴数据(生成文件,勿手改)。
// 生成:tools/gen_pokedex_static.py;数据来源 PokeAPI (CC-BY 4.0)。
#include "pokedex_static.h"

const char *pokedex_static_type_names[POKEDEX_STATIC_TYPE_COUNT] = {
    "bug",
    "dragon",
    "electric",
    "fairy",
    "fighting",
    "fire",
    "flying",
    "ghost",
    "grass",
    "ground",
    "ice",
    "normal",
    "poison",
    "psychic",
    "rock",
    "steel",
    "water",
};

const pokedex_static_entry_t pokedex_static_dex[152] = {
    [0] = {0},
    [1] = { 1, 7, 69, 8, 12, "bulbasaur", "A strange seed was planted on its back at birth. The plant sprouts and grows with this POKeMON." },
    [2] = { 2, 10, 130, 8, 12, "ivysaur", "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs." },
    [3] = { 3, 20, 1000, 8, 12, "venusaur", "The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight." },
    [4] = { 4, 6, 85, 5, 255, "charmander", "Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail." },
    [5] = { 5, 11, 190, 5, 255, "charmeleon", "When it swings its burning tail, it elevates the temperature to unbearably high levels." },
    [6] = { 6, 17, 905, 5, 6, "charizard", "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally." },
    [7] = { 7, 5, 90, 16, 255, "squirtle", "After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth." },
    [8] = { 8, 10, 225, 16, 255, "wartortle", "Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance." },
    [9] = { 9, 16, 855, 16, 255, "blastoise", "A brutal POKeMON with pressurized water jets on its shell. They are used for high speed tackles." },
    [10] = { 10, 3, 29, 0, 255, "caterpie", "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls." },
    [11] = { 11, 7, 99, 0, 255, "metapod", "This POKeMON is vulnerable to attack while its shell is soft, exposing its weak and tender body." },
    [12] = { 12, 11, 320, 0, 6, "butterfree", "In battle, it flaps its wings at high speed to release highly toxic dust into the air." },
    [13] = { 13, 3, 32, 0, 12, "weedle", "Often found in forests, eating leaves. It has a sharp venomous stinger on its head." },
    [14] = { 14, 6, 100, 0, 12, "kakuna", "Almost incapable of moving, this POKeMON can only harden its shell to protect itself from predators." },
    [15] = { 15, 10, 295, 0, 12, "beedrill", "Flies at high speed and attacks using its large venomous stingers on its forelegs and tail." },
    [16] = { 16, 3, 18, 11, 6, "pidgey", "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand." },
    [17] = { 17, 11, 300, 11, 6, "pidgeotto", "Very protective of its sprawling territorial area, this POKeMON will fiercely peck at any intruder." },
    [18] = { 18, 15, 395, 11, 6, "pidgeot", "When hunting, it skims the surface of water at high speed to pick off unwary prey such as MAGIKARP." },
    [19] = { 19, 3, 35, 11, 255, "rattata", "Bites anything when it attacks. Small and very quick, it is a common sight in many places." },
    [20] = { 20, 7, 185, 11, 255, "raticate", "It uses its whis kers to maintain its balance. It apparently slows down if they are cut off." },
    [21] = { 21, 3, 20, 11, 6, "spearow", "Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne." },
    [22] = { 22, 12, 380, 11, 6, "fearow", "With its huge and magnificent wings, it can keep aloft without ever having to land for rest." },
    [23] = { 23, 20, 69, 12, 255, "ekans", "Moves silently and stealthily. Eats the eggs of birds, such as PIDGEY and SPEAROW, whole." },
    [24] = { 24, 35, 650, 12, 255, "arbok", "It is rumored that the ferocious warning markings on its belly differ from area to area." },
    [25] = { 25, 4, 60, 2, 255, "pikachu", "When several of these POKeMON gather, their electricity could build and cause lightning storms." },
    [26] = { 26, 8, 300, 2, 255, "raichu", "Its long tail serves as a ground to protect itself from its own high voltage power." },
    [27] = { 27, 6, 120, 9, 255, "sandshrew", "Burrows deep underground in arid locations far from water. It only emerges to hunt for food." },
    [28] = { 28, 10, 295, 9, 255, "sandslash", "Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape." },
    [29] = { 29, 4, 70, 12, 255, "nidoran-f", "Although small, its venomous barbs render this POKeMON dangerous. The female has smaller horns." },
    [30] = { 30, 8, 200, 12, 255, "nidorina", "The female's horn develops slowly. Prefers physical attacks such as clawing and biting." },
    [31] = { 31, 13, 600, 12, 9, "nidoqueen", "Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves." },
    [32] = { 32, 5, 90, 12, 255, "nidoran-m", "Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom." },
    [33] = { 33, 9, 195, 12, 255, "nidorino", "An aggressive POKeMON that is quick to attack. The horn on its head secretes a powerful venom." },
    [34] = { 34, 14, 620, 12, 9, "nidoking", "It uses its powerful tail in battle to smash, constrict, then break the prey's bones." },
    [35] = { 35, 6, 75, 3, 255, "clefairy", "Its magical and cute appeal has many admirers. It is rare and found only in certain areas." },
    [36] = { 36, 13, 400, 3, 255, "clefable", "A timid fairy POKeMON that is rarely seen. It will run and hide the moment it senses people." },
    [37] = { 37, 6, 99, 5, 255, "vulpix", "At the time of birth, it has just one tail. The tail splits from its tip as it grows older." },
    [38] = { 38, 11, 199, 5, 255, "ninetales", "Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse." },
    [39] = { 39, 5, 55, 11, 3, "jigglypuff", "When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep." },
    [40] = { 40, 10, 120, 11, 3, "wigglytuff", "The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size." },
    [41] = { 41, 8, 75, 12, 6, "zubat", "Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets." },
    [42] = { 42, 16, 550, 12, 6, "golbat", "Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly." },
    [43] = { 43, 5, 54, 8, 12, "oddish", "During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds." },
    [44] = { 44, 8, 86, 8, 12, "gloom", "The fluid that oozes from its mouth isn't drool. It is a nectar that is used to attract prey." },
    [45] = { 45, 12, 186, 8, 12, "vileplume", "The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up." },
    [46] = { 46, 3, 54, 0, 8, "paras", "Burrows to suck tree roots. The mushrooms on its back grow by draw ing nutrients from the bug host." },
    [47] = { 47, 10, 295, 0, 8, "parasect", "A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places." },
    [48] = { 48, 10, 300, 0, 12, "venonat", "Lives in the shadows of tall trees where it eats insects. It is attracted by light at night." },
    [49] = { 49, 15, 125, 0, 12, "venomoth", "The dust-like scales covering its wings are color coded to indicate the kinds of poison it has." },
    [50] = { 50, 2, 8, 9, 255, "diglett", "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground." },
    [51] = { 51, 7, 333, 9, 255, "dugtrio", "A team of DIGLETT triplets. It triggers huge earthquakes by burrowing 60 miles underground." },
    [52] = { 52, 4, 42, 11, 255, "meowth", "Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change." },
    [53] = { 53, 10, 320, 11, 255, "persian", "Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness." },
    [54] = { 54, 8, 196, 16, 255, "psyduck", "While lulling its enemies with its vacant look, this wily POKeMON will use psychokinetic powers." },
    [55] = { 55, 17, 766, 16, 255, "golduck", "Often seen swim ming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa." },
    [56] = { 56, 5, 280, 4, 255, "mankey", "Extremely quick to anger. It could be docile one moment then thrashing away the next instant." },
    [57] = { 57, 10, 320, 4, 255, "primeape", "Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught." },
    [58] = { 58, 7, 190, 5, 255, "growlithe", "Very protective of its territory. It will bark and bite to repel intruders from its space." },
    [59] = { 59, 19, 1550, 5, 255, "arcanine", "A POKeMON that has been admired since the past for its beauty. It runs agilely as if on wings." },
    [60] = { 60, 6, 124, 16, 255, "poliwag", "Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand." },
    [61] = { 61, 10, 200, 16, 255, "poliwhirl", "Capable of living in or out of water. When out of water, it sweats to keep its body slimy." },
    [62] = { 62, 13, 540, 16, 4, "poliwrath", "An adept swimmer at both the front crawl and breast stroke. Easily overtakes the best human swimmers." },
    [63] = { 63, 9, 195, 13, 255, "abra", "Using its ability to read minds, it will identify impending danger and TELEPORT to safety." },
    [64] = { 64, 13, 565, 13, 255, "kadabra", "It emits special alpha waves from its body that induce headaches just by being close by." },
    [65] = { 65, 15, 480, 13, 255, "alakazam", "Its brain can out perform a super computer. Its intelligence quotient is said to be 5,000." },
    [66] = { 66, 8, 195, 4, 255, "machop", "Loves to build its muscles. It trains in all styles of martial arts to become even stronger." },
    [67] = { 67, 15, 705, 4, 255, "machoke", "Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions." },
    [68] = { 68, 16, 1300, 4, 255, "machamp", "Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon." },
    [69] = { 69, 7, 40, 8, 12, "bellsprout", "A carnivorous POKeMON that traps and eats bugs. It uses its root feet to soak up needed moisture." },
    [70] = { 70, 10, 64, 8, 12, "weepinbell", "It spits out POISONPOWDER to immobilize the enemy and then finishes it with a spray of ACID." },
    [71] = { 71, 17, 155, 8, 12, "victreebel", "Said to live in huge colonies deep in jungles, although no one has ever returned from there." },
    [72] = { 72, 9, 455, 16, 12, "tentacool", "Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid." },
    [73] = { 73, 16, 550, 16, 12, "tentacruel", "The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey." },
    [74] = { 74, 4, 200, 14, 9, "geodude", "Found in fields and mountains. Mistaking them for boulders, people often step or trip on them." },
    [75] = { 75, 10, 1050, 14, 9, "graveler", "Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction." },
    [76] = { 76, 14, 3000, 14, 9, "golem", "Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage." },
    [77] = { 77, 10, 300, 5, 255, "ponyta", "Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time." },
    [78] = { 78, 17, 950, 5, 255, "rapidash", "Very competitive, this POKeMON will chase anything that moves fast in the hopes of racing it." },
    [79] = { 79, 12, 360, 16, 13, "slowpoke", "Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack." },
    [80] = { 80, 16, 785, 16, 13, "slowbro", "The SHELLDER that is latched onto SLOWPOKE's tail is said to feed on the host's left over scraps." },
    [81] = { 81, 3, 60, 2, 15, "magnemite", "Uses anti-gravity to stay suspended. Appears without warning and uses THUNDER WAVE and similar moves." },
    [82] = { 82, 10, 600, 2, 15, "magneton", "Formed by several MAGNEMITEs linked together. They frequently appear when sunspots flare up." },
    [83] = { 83, 8, 150, 11, 6, "farfetchd", "The sprig of green onions it holds is its weapon. It is used much like a metal sword." },
    [84] = { 84, 14, 392, 11, 6, "doduo", "A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints." },
    [85] = { 85, 18, 852, 11, 6, "dodrio", "Uses its three brains to execute complex plans. While two heads sleep, one head stays awake." },
    [86] = { 86, 11, 900, 16, 255, "seel", "The protruding horn on its head is very hard. It is used for bashing through thick ice." },
    [87] = { 87, 17, 1200, 16, 10, "dewgong", "Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters." },
    [88] = { 88, 9, 300, 12, 255, "grimer", "Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories." },
    [89] = { 89, 12, 300, 12, 255, "muk", "Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison." },
    [90] = { 90, 3, 40, 16, 255, "shellder", "Its hard shell repels any kind of attack. It is vulnerable only when its shell is open." },
    [91] = { 91, 15, 1325, 16, 10, "cloyster", "When attacked, it launches its horns in quick volleys. Its innards have never been seen." },
    [92] = { 92, 13, 1, 7, 12, "gastly", "Almost invisible, this gaseous POKeMON cloaks the target and puts it to sleep without notice." },
    [93] = { 93, 16, 1, 7, 12, "haunter", "Because of its ability to slip through block walls, it is said to be from an other dimension." },
    [94] = { 94, 15, 405, 7, 12, "gengar", "Under a full moon, this POKeMON likes to mimic the shadows of people and laugh at their fright." },
    [95] = { 95, 88, 2100, 14, 9, "onix", "As it grows, the stone portions of its body harden to become similar to a diamond, but colored black." },
    [96] = { 96, 10, 324, 13, 255, "drowzee", "Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams." },
    [97] = { 97, 16, 756, 13, 255, "hypno", "When it locks eyes with an enemy, it will use a mix of PSI moves such as HYPNOSIS and CONFUSION." },
    [98] = { 98, 4, 65, 16, 255, "krabby", "Its pincers are not only powerful weapons, they are used for balance when walking sideways." },
    [99] = { 99, 13, 600, 16, 255, "kingler", "The large pincer has 10000 hp of crushing power. However, its huge size makes it unwieldy to use." },
    [100] = { 100, 5, 104, 2, 255, "voltorb", "Usually found in power plants. Easily mistaken for a POKe BALL, they have zapped many people." },
    [101] = { 101, 12, 666, 2, 255, "electrode", "It stores electric energy under very high pressure. It often explodes with little or no provocation." },
    [102] = { 102, 4, 25, 8, 13, "exeggcute", "Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms." },
    [103] = { 103, 20, 1200, 8, 13, "exeggutor", "Legend has it that on rare occasions, one of its heads will drop off and continue on as an EXEGGCUTE." },
    [104] = { 104, 4, 65, 9, 255, "cubone", "Because it never removes its skull helmet, no one has ever seen this POKeMON's real face." },
    [105] = { 105, 10, 450, 9, 255, "marowak", "The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets." },
    [106] = { 106, 15, 498, 4, 255, "hitmonlee", "When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides." },
    [107] = { 107, 14, 502, 4, 255, "hitmonchan", "While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see." },
    [108] = { 108, 12, 655, 11, 255, "lickitung", "Its tongue can be extended like a chameleon's. It leaves a tingling sensation when it licks enemies." },
    [109] = { 109, 6, 10, 12, 255, "koffing", "Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning." },
    [110] = { 110, 12, 95, 12, 255, "weezing", "Where two kinds of poison gases meet, 2 KOFFINGs can fuse into a WEEZING over many years." },
    [111] = { 111, 10, 1150, 9, 14, "rhyhorn", "Its massive bones are 1000 times harder than human bones. It can easily knock a trailer flying." },
    [112] = { 112, 19, 1200, 9, 14, "rhydon", "Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees." },
    [113] = { 113, 11, 346, 11, 255, "chansey", "A rare and elusive POKeMON that is said to bring happiness to those who manage to get it." },
    [114] = { 114, 10, 350, 8, 255, "tangela", "The whole body is swathed with wide vines that are similar to sea weed. Its vines shake as it walks." },
    [115] = { 115, 22, 800, 11, 255, "kangaskhan", "The infant rarely ventures out of its mother's protective pouch until it is 3 years old." },
    [116] = { 116, 4, 80, 16, 255, "horsea", "Known to shoot down flying bugs with precision blasts of ink from the surface of the water." },
    [117] = { 117, 12, 250, 16, 255, "seadra", "Capable of swim ming backwards by rapidly flapping its wing-like pectoral fins and stout tail." },
    [118] = { 118, 6, 150, 16, 255, "goldeen", "Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen." },
    [119] = { 119, 13, 390, 16, 255, "seaking", "In the autumn spawning season, they can be seen swimming power fully up rivers and creeks." },
    [120] = { 120, 8, 345, 16, 255, "staryu", "An enigmatic POKeMON that can effortlessly regenerate any appendage it loses in battle." },
    [121] = { 121, 11, 800, 16, 13, "starmie", "Its central core glows with the seven colors of the rainbow. Some people value the core as a gem." },
    [122] = { 122, 13, 545, 13, 3, "mr-mime", "If interrupted while it is miming, it will slap around the offender with its broad hands." },
    [123] = { 123, 15, 560, 0, 6, "scyther", "With ninja-like agility and speed, it can create the illusion that there is more than one." },
    [124] = { 124, 14, 406, 10, 13, "jynx", "It seductively wiggles its hips as it walks. It can cause people to dance in unison with it." },
    [125] = { 125, 11, 300, 2, 255, "electabuzz", "Normally found near power plants, they can wander away and cause major blackouts in cities." },
    [126] = { 126, 13, 445, 5, 255, "magmar", "Its body always burns with an orange glow that enables it to hide perfectly among flames." },
    [127] = { 127, 15, 550, 0, 255, "pinsir", "If it fails to crush the victim in its pincers, it will swing it around and toss it hard." },
    [128] = { 128, 14, 884, 11, 255, "tauros", "When it targets an enemy, it charges furiously while whipping its body with its long tails." },
    [129] = { 129, 9, 100, 16, 255, "magikarp", "In the distant past, it was somewhat stronger than the horribly weak descendants that exist today." },
    [130] = { 130, 65, 2350, 16, 6, "gyarados", "Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage." },
    [131] = { 131, 25, 2200, 16, 10, "lapras", "A POKeMON that has been over hunted almost to extinction. It can ferry people across the water." },
    [132] = { 132, 3, 40, 11, 255, "ditto", "Capable of copying an enemy's genetic code to instantly transform itself into a duplicate of the enemy." },
    [133] = { 133, 3, 65, 11, 255, "eevee", "Its genetic code is irregular. It may mutate if it is exposed to radiation from element STONEs." },
    [134] = { 134, 10, 290, 16, 255, "vaporeon", "Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid's." },
    [135] = { 135, 8, 245, 2, 255, "jolteon", "It accumulates negative ions in the atmosphere to blast out 10000- volt lightning bolts." },
    [136] = { 136, 9, 250, 5, 255, "flareon", "When storing thermal energy in its body, its temperature could soar to over 1600 degrees." },
    [137] = { 137, 8, 365, 11, 255, "porygon", "A POKeMON that consists entirely of programming code. Capable of moving freely in cyberspace." },
    [138] = { 138, 4, 75, 14, 16, "omanyte", "Although long extinct, in rare cases, it can be genetically resurrected from fossils." },
    [139] = { 139, 10, 350, 14, 16, "omastar", "A prehistoric POKeMON that died out when its heavy shell made it impossible to catch prey." },
    [140] = { 140, 5, 115, 14, 16, "kabuto", "A POKeMON that was resurrected from a fossil found in what was once the ocean floor eons ago." },
    [141] = { 141, 13, 405, 14, 16, "kabutops", "Its sleek shape is perfect for swim ming. It slashes prey with its claws and drains the body fluids." },
    [142] = { 142, 18, 590, 14, 6, "aerodactyl", "A ferocious, pre historic POKeMON that goes for the enemy's throat with its serrated saw-like fangs." },
    [143] = { 143, 21, 4600, 11, 255, "snorlax", "Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful." },
    [144] = { 144, 17, 554, 10, 6, "articuno", "A legendary bird POKeMON that is said to appear to doomed people who are lost in icy mountains." },
    [145] = { 145, 16, 526, 2, 6, "zapdos", "A legendary bird POKeMON that is said to appear from clouds while dropping enormous lightning bolts." },
    [146] = { 146, 20, 600, 5, 6, "moltres", "Known as the legendary bird of fire. Every flap of its wings creates a dazzling flash of flames." },
    [147] = { 147, 18, 33, 1, 255, "dratini", "Long considered a mythical POKeMON until recently when a small colony was found living underwater." },
    [148] = { 148, 40, 165, 1, 255, "dragonair", "A mystical POKeMON that exudes a gentle aura. Has the ability to change climate conditions." },
    [149] = { 149, 22, 2100, 1, 6, "dragonite", "An extremely rarely seen marine POKeMON. Its intelligence is said to match that of humans." },
    [150] = { 150, 20, 1220, 13, 255, "mewtwo", "It was created by a scientist after years of horrific gene splicing and DNA engineering experiments." },
    [151] = { 151, 4, 40, 13, 255, "mew", "So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide." },
};
